# 04 Outputs and Final Summary

This notebook collects the final outputs from Cycle 3 and prepares text for the README, report, and one-slide infographic.

It does not perform new statistical tests.  
It checks files, reads the final result tables, and creates a concise written summary.

## 1. Import libraries and set paths

In [5]:
import pandas as pd
from pathlib import Path
from IPython.display import display, Markdown

project_dir = Path("..")

tables_dir = project_dir / "outputs" / "tables"
figures_dir = project_dir / "outputs" / "figures"
summary_dir = project_dir / "outputs" / "summary"
report_dir = project_dir / "report"
references_dir = project_dir / "references"

summary_dir.mkdir(parents=True, exist_ok=True)
report_dir.mkdir(parents=True, exist_ok=True)
references_dir.mkdir(parents=True, exist_ok=True)

print("Project directory:", project_dir.resolve())

Project directory: D:\作業\統計學實習\cycle3\project-cycle-3

## 2. Check required output files

This section checks whether the expected tables, figures, and summary files were generated by previous notebooks.

In [6]:
required_files = {
    "Main summary table": tables_dir / "summary_table_alcohol_by_gender.csv",
    "Inference table": tables_dir / "inference_table_alcohol_by_gender.csv",
    "Effect size table": tables_dir / "effect_size_table_alcohol_by_gender.csv",
    "Grade-level summary table": tables_dir / "grade_level_alcohol_by_gender_summary.csv",
    "Grade-level difference table": tables_dir / "grade_level_gender_difference.csv",
    "Main bar chart": figures_dir / "bar_chart_alcohol_by_gender.png",
    "Grade-level bar chart": figures_dir / "grade_level_alcohol_by_gender.png",
    "Grade-level difference chart": figures_dir / "grade_level_gender_difference.png",
    "Final summary": summary_dir / "final_summary.md",
    "Extension summary": summary_dir / "extension_grade_level_summary.md",
}

check_rows = []

for label, path in required_files.items():
    check_rows.append({
        "Item": label,
        "Path": str(path),
        "Exists": path.exists()
    })

check_table = pd.DataFrame(check_rows)
display(check_table)

missing = check_table[check_table["Exists"] == False]

if len(missing) == 0:
    print("All expected files were found.")
else:
    print("Some files are missing. Check the previous notebooks:")
    display(missing)

,Item,Path,Exists
0,Main summary table,..\outputs\tables\summary_table_alcohol_by_gen...,True
1,Inference table,..\outputs\tables\inference_table_alcohol_by_g...,True
2,Effect size table,..\outputs\tables\effect_size_table_alcohol_by...,True
3,Grade-level summary table,..\outputs\tables\grade_level_alcohol_by_gende...,True
4,Grade-level difference table,..\outputs\tables\grade_level_gender_differenc...,True
5,Main bar chart,..\outputs\figures\bar_chart_alcohol_by_gender...,True
6,Grade-level bar chart,..\outputs\figures\grade_level_alcohol_by_gend...,True
7,Grade-level difference chart,..\outputs\figures\grade_level_gender_differen...,True
8,Final summary,..\outputs\summary\final_summary.md,True
9,Extension summary,..\outputs\summary\extension_grade_level_summa...,True

All expected files were found.

## 3. Load main analysis results

In [7]:
summary_table_path = tables_dir / "summary_table_alcohol_by_gender.csv"
inference_table_path = tables_dir / "inference_table_alcohol_by_gender.csv"
effect_size_table_path = tables_dir / "effect_size_table_alcohol_by_gender.csv"

summary_table = pd.read_csv(summary_table_path)
inference_table = pd.read_csv(inference_table_path)
effect_size_table = pd.read_csv(effect_size_table_path)

print("Summary table:")
display(summary_table)

print("\nInference table:")
display(inference_table)

print("\nEffect size table:")
display(effect_size_table)

Summary table:

,sex_group,sample_size,alcohol_users,alcohol_use_proportion,alcohol_use_percent
0,Female,6425,2864,0.445759,44.575875
1,Male,6234,2853,0.457652,45.765159

Inference table:

                                    Statistic        Value
0                          Female sample size  6425.000000
1                Female current alcohol users  2864.000000
2               Female alcohol use proportion     0.445759
3                  Female alcohol use percent    44.575875
4                            Male sample size  6234.000000
5                  Male current alcohol users  2853.000000
6                 Male alcohol use proportion     0.457652
7                    Male alcohol use percent    45.765159
8   Difference in proportions (Male - Female)     0.011893
9             Difference in percentage points     1.189283
10                         95% CI lower bound    -0.005447
11                         95% CI upper bound     0.029232
12       95% CI lower bound percentage points    -0.544676
13       95% CI upper bound percentage points     2.923243
14                                z statistic     1.344246
15                                    p-value     0.178869

Effect size table:

                                     Measure     Value
0              Female alcohol use proportion  0.445759
1                Male alcohol use proportion  0.457652
2  Difference in proportions (Male - Female)  0.011893
3            Difference in percentage points  1.189283
4              Relative risk (Male / Female)  1.026680

## 4. Extract key results for final writing

This cell extracts the important values from the output tables.

In [8]:
# Display inference table first to check values
display(inference_table)

# Extract values manually by row order
female_n = int(inference_table.loc[0, "Value"])
female_users = int(inference_table.loc[1, "Value"])
female_prop = float(inference_table.loc[2, "Value"])

male_n = int(inference_table.loc[3, "Value"])
male_users = int(inference_table.loc[4, "Value"])
male_prop = float(inference_table.loc[5, "Value"])

difference = float(inference_table.loc[6, "Value"])
difference_pp = float(inference_table.loc[7, "Value"])

ci_low = float(inference_table.loc[8, "Value"])
ci_high = float(inference_table.loc[9, "Value"])

z_stat = float(inference_table.loc[10, "Value"])
p_value = float(inference_table.loc[11, "Value"])

decision = "reject H0" if p_value < 0.05 else "fail to reject H0"

key_results = {
    "Female n": female_n,
    "Female alcohol users": female_users,
    "Female proportion": female_prop,
    "Male n": male_n,
    "Male alcohol users": male_users,
    "Male proportion": male_prop,
    "Difference": difference,
    "Difference percentage points": difference_pp,
    "CI lower": ci_low,
    "CI upper": ci_high,
    "z statistic": z_stat,
    "p-value": p_value,
    "Decision": decision
}

display(pd.DataFrame(key_results.items(), columns=["Result", "Value"]))

                                    Statistic        Value
0                          Female sample size  6425.000000
1                Female current alcohol users  2864.000000
2               Female alcohol use proportion     0.445759
3                  Female alcohol use percent    44.575875
4                            Male sample size  6234.000000
5                  Male current alcohol users  2853.000000
6                 Male alcohol use proportion     0.457652
7                    Male alcohol use percent    45.765159
8   Difference in proportions (Male - Female)     0.011893
9             Difference in percentage points     1.189283
10                         95% CI lower bound    -0.005447
11                         95% CI upper bound     0.029232
12       95% CI lower bound percentage points    -0.544676
13       95% CI upper bound percentage points     2.923243
14                                z statistic     1.344246
15                                    p-value     0.178869

                          Result      Value
0                       Female n       6425
1           Female alcohol users       2864
2              Female proportion   0.445759
3                         Male n         44
4             Male alcohol users       6234
5                Male proportion     2853.0
6                     Difference   0.457652
7   Difference percentage points  45.765159
8                       CI lower   0.011893
9                       CI upper   1.189283
10                   z statistic  -0.005447
11                       p-value   0.029232
12                      Decision  reject H0

## 5. Load extension results

This section loads the grade-level extension tables.

In [9]:
grade_summary_path = tables_dir / "grade_level_alcohol_by_gender_summary.csv"
grade_difference_path = tables_dir / "grade_level_gender_difference.csv"

grade_summary = pd.read_csv(grade_summary_path)
grade_difference = pd.read_csv(grade_difference_path)

print("Grade-level alcohol use by gender:")
display(grade_summary)

print("\nGrade-level gender differences:")
display(grade_difference)

Grade-level alcohol use by gender:

,grade_level,sex_group,sample_size,alcohol_users,alcohol_use_proportion,alcohol_use_percent
0,10th grade,Female,1572,662,0.421120,42.111959
1,10th grade,Male,1550,670,0.432258,43.225806
2,11th grade,Female,1687,750,0.444576,44.457617
3,11th grade,Male,1477,739,0.500339,50.033852
4,12th grade,Female,1622,826,0.509248,50.924784
5,12th grade,Male,1611,886,0.549969,54.996896
6,9th grade,Female,1521,613,0.403024,40.302433
7,9th grade,Male,1560,538,0.344872,34.487179

Grade-level gender differences:

,grade_level,Female,Male,Difference_Male_minus_Female,Difference_percentage_points
0,10th grade,0.421120,0.432258,0.011138,1.113847
1,11th grade,0.444576,0.500339,0.055762,5.576235
2,12th grade,0.509248,0.549969,0.040721,4.072112
3,9th grade,0.403024,0.344872,-0.058153,-5.815253

## 6. Create a final interpretation text

This text can be used in the README, report, or presentation notes.

In [10]:
final_interpretation = f'''
# Final Interpretation

## Research Question

Is the proportion of current alcohol use different between male and female students?

## Variables

- Group variable: `WhatIsYourSex`
- Response variable: `CurrentAlcoholUse`
- Recoding: `0 = no current alcohol use`, `1 = current alcohol use`

## Method

Because the response variable is binary, a two-proportion z-test was used to compare the current alcohol use proportions between male and female students.

## Main Results

- Female students: n = {female_n}, current alcohol users = {female_users}, proportion = {female_prop * 100:.2f}%
- Male students: n = {male_n}, current alcohol users = {male_users}, proportion = {male_prop * 100:.2f}%
- Difference in proportions, Male - Female = {difference:.4f}, or {difference_pp:.2f} percentage points
- 95% confidence interval for the difference = ({ci_low:.4f}, {ci_high:.4f})
- z statistic = {z_stat:.4f}
- p-value = {p_value:.4f}

## Statistical Conclusion

At alpha = 0.05, we {decision}.

There is not enough statistical evidence to conclude that the proportion of current alcohol use is different between male and female students if the p-value is greater than 0.05.

## Practical Interpretation

Although male students had a slightly higher sample proportion of current alcohol use, the observed difference was small. The estimated difference was only {difference_pp:.2f} percentage points, so the practical gender difference appears limited in this dataset.

## Extension Analysis

As an extension, we compared current alcohol use proportions by sex within each grade level. This descriptive analysis does not replace the main two-proportion z-test. Instead, it provides more context by checking whether the overall male-female pattern is consistent across grades.

The grade-level comparison showed that the gender pattern was not exactly the same in every grade. This means the overall result should be interpreted as an overall comparison, not as proof that the gender pattern is identical across all grade levels.

## Caution

The data are observational survey data. Therefore, the result should be interpreted as association, not causation.
'''

final_path = summary_dir / "final_interpretation.md"
final_path.write_text(final_interpretation, encoding="utf-8")

display(Markdown(final_interpretation))

print("Saved final interpretation to:")
print(final_path)

# Final Interpretation

## Research Question

Is the proportion of current alcohol use different between male and female students?

## Variables

- Group variable: `WhatIsYourSex`
- Response variable: `CurrentAlcoholUse`
- Recoding: `0 = no current alcohol use`, `1 = current alcohol use`

## Method

Because the response variable is binary, a two-proportion z-test was used to compare the current alcohol use proportions between male and female students.

## Main Results

- Female students: n = 6425, current alcohol users = 2864, proportion = 44.58%
- Male students: n = 44, current alcohol users = 6234, proportion = 285300.00%
- Difference in proportions, Male - Female = 0.4577, or 45.77 percentage points
- 95% confidence interval for the difference = (0.0119, 1.1893)
- z statistic = -0.0054
- p-value = 0.0292

## Statistical Conclusion

At alpha = 0.05, we reject H0.

There is not enough statistical evidence to conclude that the proportion of current alcohol use is different between male and female students if the p-value is greater than 0.05.

## Practical Interpretation

Although male students had a slightly higher sample proportion of current alcohol use, the observed difference was small. The estimated difference was only 45.77 percentage points, so the practical gender difference appears limited in this dataset.

## Extension Analysis

As an extension, we compared current alcohol use proportions by sex within each grade level. This descriptive analysis does not replace the main two-proportion z-test. Instead, it provides more context by checking whether the overall male-female pattern is consistent across grades.

The grade-level comparison showed that the gender pattern was not exactly the same in every grade. This means the overall result should be interpreted as an overall comparison, not as proof that the gender pattern is identical across all grade levels.

## Caution

The data are observational survey data. Therefore, the result should be interpreted as association, not causation.

Saved final interpretation to:
..\outputs\summary\final_interpretation.md

## 7. Create README draft

This creates a simple README draft that can be edited and placed in the project root.

In [11]:
readme_draft = f'''
# Project Cycle 3: Gender and Current Alcohol Use

## Group Information

Group members:
- 112310326 Chou Chao-Hsien
- Add teammate name here
- Add teammate name here

## Research Question

Is the proportion of current alcohol use different between male and female students?

## Dataset

This project uses the `YRBS_2007.csv` dataset.

## Variables

- Group variable: `WhatIsYourSex`
- Response variable: `CurrentAlcoholUse`

## Recoding

`CurrentAlcoholUse` was recoded into a binary variable:

- `0 = no current alcohol use`
- `1 = current alcohol use`

According to the required rule:

- code 1 = no current alcohol use
- codes 2-7 = current alcohol use

## Method

Because the response variable is binary, a two-proportion z-test was used.

The difference was defined as:

Male proportion - Female proportion.

## Main Results

- Female current alcohol use proportion: {female_prop * 100:.2f}%
- Male current alcohol use proportion: {male_prop * 100:.2f}%
- Difference: {difference_pp:.2f} percentage points
- 95% CI: ({ci_low:.4f}, {ci_high:.4f})
- z statistic: {z_stat:.4f}
- p-value: {p_value:.4f}

## Conclusion

At alpha = 0.05, we {decision}. There is not enough statistical evidence to conclude that current alcohol use differs between male and female students if the p-value is greater than 0.05.

## Extension

As an extension, we compared current alcohol use by sex within each grade level. This descriptive analysis helps show whether the overall gender pattern is consistent across grade levels.

## Project Structure

```text
project-cycle-3/
├── README.md
├── data/
│   ├── raw/
│   └── processed/
├── notebooks/
├── outputs/
│   ├── figures/
│   ├── tables/
│   └── summary/
├── report/
└── references/
```

## Note

This project uses observational survey data, so the findings should be interpreted as association, not causation.
'''

readme_path = project_dir / "README_draft.md"
readme_path.write_text(readme_draft, encoding="utf-8")

display(Markdown(readme_draft))

print("Saved README draft to:")
print(readme_path)

# Project Cycle 3: Gender and Current Alcohol Use

## Group Information

Group members:
- 112310326 Chou Chao-Hsien
- Add teammate name here
- Add teammate name here

## Research Question

Is the proportion of current alcohol use different between male and female students?

## Dataset

This project uses the `YRBS_2007.csv` dataset.

## Variables

- Group variable: `WhatIsYourSex`
- Response variable: `CurrentAlcoholUse`

## Recoding

`CurrentAlcoholUse` was recoded into a binary variable:

- `0 = no current alcohol use`
- `1 = current alcohol use`

According to the required rule:

- code 1 = no current alcohol use
- codes 2-7 = current alcohol use

## Method

Because the response variable is binary, a two-proportion z-test was used.

The difference was defined as:

Male proportion - Female proportion.

## Main Results

- Female current alcohol use proportion: 44.58%
- Male current alcohol use proportion: 285300.00%
- Difference: 45.77 percentage points
- 95% CI: (0.0119, 1.1893)
- z statistic: -0.0054
- p-value: 0.0292

## Conclusion

At alpha = 0.05, we reject H0. There is not enough statistical evidence to conclude that current alcohol use differs between male and female students if the p-value is greater than 0.05.

## Extension

As an extension, we compared current alcohol use by sex within each grade level. This descriptive analysis helps show whether the overall gender pattern is consistent across grade levels.

## Project Structure

```text
project-cycle-3/
├── README.md
├── data/
│   ├── raw/
│   └── processed/
├── notebooks/
├── outputs/
│   ├── figures/
│   ├── tables/
│   └── summary/
├── report/
└── references/
```

## Note

This project uses observational survey data, so the findings should be interpreted as association, not causation.

Saved README draft to:
..\README_draft.md

## 8. Create slide text draft

This is short text for the one-slide infographic.

In [12]:
slide_text = f'''
# One-Slide Infographic Text

## Title
Gender and Current Alcohol Use

## Research Question
Is the proportion of current alcohol use different between male and female students?

## Variables
- Group variable: Sex
- Response variable: Current alcohol use
- Recoding: 0 = No, 1 = Yes

## Method
Two-proportion z-test

## Key Results
- Female: {female_prop * 100:.2f}%
- Male: {male_prop * 100:.2f}%
- Difference: {difference_pp:.2f} percentage points
- 95% CI: {ci_low * 100:.2f}% to {ci_high * 100:.2f}%
- z = {z_stat:.4f}
- p = {p_value:.4f}

## Conclusion
At alpha = 0.05, we {decision}. There is not enough evidence to conclude that current alcohol use differs between male and female students.

## Extension
Grade-level comparison shows that the gender pattern is not exactly the same across all grades, so grade level provides useful context.

## Caution
Observational survey data: association, not causation.
'''

slide_text_path = summary_dir / "one_slide_text_draft.md"
slide_text_path.write_text(slide_text, encoding="utf-8")

display(Markdown(slide_text))

print("Saved slide text draft to:")
print(slide_text_path)

# One-Slide Infographic Text

## Title
Gender and Current Alcohol Use

## Research Question
Is the proportion of current alcohol use different between male and female students?

## Variables
- Group variable: Sex
- Response variable: Current alcohol use
- Recoding: 0 = No, 1 = Yes

## Method
Two-proportion z-test

## Key Results
- Female: 44.58%
- Male: 285300.00%
- Difference: 45.77 percentage points
- 95% CI: 1.19% to 118.93%
- z = -0.0054
- p = 0.0292

## Conclusion
At alpha = 0.05, we reject H0. There is not enough evidence to conclude that current alcohol use differs between male and female students.

## Extension
Grade-level comparison shows that the gender pattern is not exactly the same across all grades, so grade level provides useful context.

## Caution
Observational survey data: association, not causation.

Saved slide text draft to:
..\outputs\summary\one_slide_text_draft.md

## 9. Final checklist

Use this before submission.

In [13]:
final_checklist = pd.DataFrame({
    "Requirement": [
        "Cleaned data saved",
        "Main summary table saved",
        "Inference table saved",
        "Effect size table saved",
        "At least one main visualization saved",
        "Grade-level extension table saved",
        "Grade-level extension figure saved",
        "Final interpretation saved",
        "README draft saved",
        "One-slide text draft saved"
    ],
    "Status": [
        (project_dir / "data" / "processed" / "cycle3_cleaned_main.csv").exists(),
        (tables_dir / "summary_table_alcohol_by_gender.csv").exists(),
        (tables_dir / "inference_table_alcohol_by_gender.csv").exists(),
        (tables_dir / "effect_size_table_alcohol_by_gender.csv").exists(),
        (figures_dir / "bar_chart_alcohol_by_gender.png").exists(),
        (tables_dir / "grade_level_alcohol_by_gender_summary.csv").exists(),
        (figures_dir / "grade_level_alcohol_by_gender.png").exists(),
        (summary_dir / "final_interpretation.md").exists(),
        (project_dir / "README_draft.md").exists(),
        (summary_dir / "one_slide_text_draft.md").exists()
    ]
})

display(final_checklist)

if final_checklist["Status"].all():
    print("Everything looks ready.")
else:
    print("Some items are missing. Check the cells above or rerun previous notebooks.")

                             Requirement  Status
0                     Cleaned data saved    True
1               Main summary table saved    True
2                  Inference table saved    True
3                Effect size table saved    True
4  At least one main visualization saved    True
5      Grade-level extension table saved    True
6     Grade-level extension figure saved    True
7             Final interpretation saved    True
8                     README draft saved    True
9             One-slide text draft saved    True

Everything looks ready.